url: "https://gdscbilecik.github.io" # the base hostname & protocol for your site, e.g. http://example.com
baseurl: "" # the subpath of your site, e.g. /blog
title: "GDSC Bilecik" # the name of your site, e.g. ACME Corp.

lang: "tr-TR" # the language code of your site, e.g. en-US
